import type { NextPage } from 'next'
import Head from 'next/head'
import QRCodePlugin from '../components/scan1/QRCodePlugin'
import Scanner from '../components/scan2/Scanner'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Developed with Quagga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>
      {/* <QRCodePlugin /> */}
      <Scanner />
      </>
  )
}

export default Home
