import type { NextPage } from 'next'
import Head from 'next/head'
import QRCodePlugin from '../components/scan1/QRCodePlugin'
import Scanner from '../components/scan2/Scanner'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Developed with Quagga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <QRCodePlugin /> */}
      <Scanner />
    </div>
  )
}

export default Home
